---
kind: pipeline
name: build

workspace:
  base: /go
  path: src/yunion.io/x/onecloud

steps:
- name: build
  image: d3lx/golang:yunion
  commands:
  - make
  when:
    event:
    - pull_request
    - tag

trigger:
  event:
  - pull_request
  - tag

---
kind: pipeline
name: release

steps:
- name: release-img
  image: plugins/docker
  settings:
    repo: registry.cn-beijing.aliyuncs.com/yunionio/onecloud
    registry: registry.cn-beijing.aliyuncs.com
    tags: "{DRONE_TAG}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

trigger:
  event:
  - tag
  status:
  - success

depends_on:
- build
