# This is how to tell Travis to use the fast container-based test
# runner instead of the slow VM-based one.
sudo: false

dist: xenial

services:
  - docker

language: go
go_import_path: yunion.io/x/onecloud

# Only clone the most recent commit.
git:
  depth: 8

script:
- chmod -R o+w $PWD
- docker pull yunionio/onecloud-ci:latest
- make docker-build F="-j2 ONECLOUD_CI_BUILD=1"
- chmod -R o-x $PWD
