ProjectListResponse:
  type: object
  properties:
    limit:
      type: integer
      example: 20
    offset:
      type: integer
      example: 0
    total:
      type: integer
      description: 总量
    projects:
      type: array
      items:
        $ref: "#/Project"

ProjectGetResponse:
  type: object
  properties:
    project:
      type: object
      $ref: "#/Project"

ProjectPutRequestInput:
  type: object
  properties:
    name:
      type: string
      description: 项目的名称
    description:  
      type: string
      description: 项目的描述

ProjectCreateInput:
  type: object
  properties:
    name:
      type: string
      required: true
      description: 项目的名称
    description:
      type: string
      description: 项目的描述

Project:
  type: object
  description: 项目
  properties:
    id:
      type: string
      description: 项目ID
      readOnly: true
    name:
      type: string
      description: 项目名，全局唯一
    can_delete:
      type: boolean
      description: 是否可以删除
